export interface Migration {
  version: number;
  name: string;
  statements: string[];
}

export const migrations: Migration[] = [
  {
    version: 1,
    name: "create_core_tables",
    statements: [
      `CREATE TABLE IF NOT EXISTS settings (
        id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
        shop_name VARCHAR(200) NOT NULL DEFAULT 'ข้าวกล่องเดลิเวอรี ส่งด่วนมื้อเที่ยง',
        shop_address VARCHAR(500) NOT NULL DEFAULT 'มหาวิทยาลัยมหาสารคาม ต.ขามเรียง อ.กันทรวิชัย จ.มหาสารคาม',
        shop_latitude DOUBLE NOT NULL DEFAULT 16.246825,
        shop_longitude DOUBLE NOT NULL DEFAULT 103.252021,
        box_price DECIMAL(10,2) NOT NULL DEFAULT 65.00,
        box_cost DECIMAL(10,2) NOT NULL DEFAULT 40.00,
        rider_base_fee DECIMAL(10,2) NOT NULL DEFAULT 15.00,
        rider_fee_per_km_per_box DECIMAL(10,2) NOT NULL DEFAULT 2.00,
        rider_speed_kmh DOUBLE NOT NULL DEFAULT 30,
        max_orders_per_rider INT NOT NULL DEFAULT 3,
        max_boxes_per_order INT NOT NULL DEFAULT 3,
        departure_time CHAR(5) NOT NULL DEFAULT '11:30',
        delivery_window_minutes INT NOT NULL DEFAULT 60,
        service_minutes_per_stop DOUBLE NOT NULL DEFAULT 2,
        road_distance_factor DOUBLE NOT NULL DEFAULT 1.3,
        service_radius_km DOUBLE NOT NULL DEFAULT 3,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
      `INSERT IGNORE INTO settings (id) VALUES (1)`,
      `CREATE TABLE IF NOT EXISTS customers (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        first_name VARCHAR(100) NOT NULL,
        last_name VARCHAR(100) NOT NULL DEFAULT '',
        phone VARCHAR(30) NOT NULL,
        address VARCHAR(500) NOT NULL DEFAULT '',
        latitude DOUBLE NOT NULL,
        longitude DOUBLE NOT NULL,
        note VARCHAR(500) NOT NULL DEFAULT '',
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX idx_customers_name (first_name, last_name),
        INDEX idx_customers_phone (phone)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
      `CREATE TABLE IF NOT EXISTS riders (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(150) NOT NULL,
        phone VARCHAR(30) NOT NULL DEFAULT '',
        vehicle_plate VARCHAR(30) NOT NULL DEFAULT '',
        active TINYINT(1) NOT NULL DEFAULT 1,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
      `CREATE TABLE IF NOT EXISTS delivery_plans (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        delivery_date DATE NOT NULL,
        objective VARCHAR(20) NOT NULL,
        seed INT UNSIGNED NOT NULL,
        revision INT UNSIGNED NOT NULL DEFAULT 1,
        status VARCHAR(20) NOT NULL DEFAULT 'draft',
        departure_time CHAR(5) NOT NULL,
        deadline_time CHAR(5) NOT NULL,
        settings_snapshot LONGTEXT NOT NULL,
        summary LONGTEXT NOT NULL,
        signature LONGTEXT NOT NULL,
        explored_signatures LONGTEXT NOT NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        confirmed_at DATETIME NULL,
        cancelled_at DATETIME NULL,
        completed_at DATETIME NULL,
        INDEX idx_plans_date_status (delivery_date, status)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
      `CREATE TABLE IF NOT EXISTS orders (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        customer_id INT UNSIGNED NOT NULL,
        delivery_date DATE NOT NULL,
        boxes INT UNSIGNED NOT NULL,
        unit_price DECIMAL(10,2) NOT NULL,
        status VARCHAR(20) NOT NULL DEFAULT 'pending',
        note VARCHAR(500) NOT NULL DEFAULT '',
        plan_id INT UNSIGNED NULL,
        delivered_at DATETIME NULL,
        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
        INDEX idx_orders_date_status (delivery_date, status),
        CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT,
        CONSTRAINT fk_orders_plan FOREIGN KEY (plan_id) REFERENCES delivery_plans (id) ON DELETE SET NULL
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
      `CREATE TABLE IF NOT EXISTS plan_routes (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        plan_id INT UNSIGNED NOT NULL,
        sequence INT UNSIGNED NOT NULL,
        job_code VARCHAR(20) NOT NULL,
        color CHAR(7) NOT NULL,
        rider_id INT UNSIGNED NULL,
        status VARCHAR(20) NOT NULL DEFAULT 'pending',
        order_count INT UNSIGNED NOT NULL,
        box_count INT UNSIGNED NOT NULL,
        distance_km DOUBLE NOT NULL,
        duration_minutes DOUBLE NOT NULL,
        rider_fee DECIMAL(10,2) NOT NULL,
        revenue DECIMAL(10,2) NOT NULL,
        food_cost DECIMAL(10,2) NOT NULL,
        profit DECIMAL(10,2) NOT NULL,
        path LONGTEXT NOT NULL,
        started_at DATETIME NULL,
        completed_at DATETIME NULL,
        UNIQUE KEY uq_routes_job_code (job_code),
        INDEX idx_routes_plan (plan_id),
        CONSTRAINT fk_routes_plan FOREIGN KEY (plan_id) REFERENCES delivery_plans (id) ON DELETE CASCADE,
        CONSTRAINT fk_routes_rider FOREIGN KEY (rider_id) REFERENCES riders (id) ON DELETE SET NULL
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
      `CREATE TABLE IF NOT EXISTS plan_stops (
        id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        route_id INT UNSIGNED NOT NULL,
        sequence INT UNSIGNED NOT NULL,
        order_id INT UNSIGNED NULL,
        customer_id INT UNSIGNED NULL,
        customer_name VARCHAR(250) NOT NULL,
        phone VARCHAR(30) NOT NULL,
        address VARCHAR(500) NOT NULL,
        latitude DOUBLE NOT NULL,
        longitude DOUBLE NOT NULL,
        boxes INT UNSIGNED NOT NULL,
        leg_distance_km DOUBLE NOT NULL,
        cumulative_distance_km DOUBLE NOT NULL,
        arrival_minutes DOUBLE NOT NULL,
        eta CHAR(5) NOT NULL,
        late TINYINT(1) NOT NULL DEFAULT 0,
        status VARCHAR(20) NOT NULL DEFAULT 'pending',
        delivered_at DATETIME NULL,
        INDEX idx_stops_route (route_id),
        INDEX idx_stops_order (order_id),
        CONSTRAINT fk_stops_route FOREIGN KEY (route_id) REFERENCES plan_routes (id) ON DELETE CASCADE,
        CONSTRAINT fk_stops_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE SET NULL,
        CONSTRAINT fk_stops_customer FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE SET NULL
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
    ],
  },
  {
    version: 2,
    name: "add_route_geometry_and_simulation_flags",
    statements: [
      "ALTER TABLE plan_routes ADD COLUMN geometry LONGTEXT NULL AFTER path",
      "ALTER TABLE orders ADD COLUMN is_simulated TINYINT(1) NOT NULL DEFAULT 0 AFTER note",
      "ALTER TABLE customers ADD COLUMN is_simulated TINYINT(1) NOT NULL DEFAULT 0 AFTER note",
      "UPDATE orders SET is_simulated = 1, note = '' WHERE note = 'simulated'",
      "UPDATE customers SET is_simulated = 1, note = '' WHERE note = 'simulated'",
      "CREATE INDEX idx_orders_simulated ON orders (is_simulated)",
    ],
  },
];
